### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by codecaiine**
- We optimize some slow queries in the database.

 Add screenshots of visit data before optimization.
anayse_from_visit_beforeOPTMZ

 Add screenshots of visit data after improving speed.
anayse_from_visit_afterOPTMZ

Add screenshots of owner data before optimization.
anayse_from_owner_beforeOPTMZ

 Add screenshots of owner data after improving speed.
anayse_from_owner_afterOPTMZ

## Bellow is the required changes from the reviewer

- SELECT COUNT(*) FROM visits where animal_id = 4;

Capture1

Capture2

- SELECT * FROM visits where vet_id = 2;

Capture3a

Capture3b

- SELECT * FROM owners where email = 'owner_18327@mail.com';

Capture4

Capture6

### Find below the Change requested from the second and last Reviewer (Since this is our last chance of review, we plead that you write us on slack in case of anything). 

- SELECT COUNT(*) FROM visits where animal_id = 4;

Capture1

Capture2

- SELECT * FROM visits where vet_id = 2;

Capture3

Capture4

- SELECT * FROM owners where email = 'owner_18327@mail.com';

Capture5

Capture6

### CODE REVIEW

**Comment by Davidosky007** [comment]
## Hi @codecaiine @OLIPLICHE 👋, 

Good job so far! 💪 
* Nice job using the right SQL queries ✔️ 
* Descriptive commit messages ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
* Kindly provide a complete screenshot of the result for the ` EXPLAIN ANALYZE` command for each of these queries you should have `6` screenshots 
*  ` SELECT COUNT(*) FROM visits where animal_id = 4;`
* `SELECT * FROM visits where vet_id = 2;`
* `SELECT * FROM owners where email = 'owner_18327@mail.com';`  check project requirement [Here](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_performance_audit.md#:~:text=In%20your%20pull%20request%20description%20include%20screenshots%20with%20EXPLAIN%20ANALYZE%20results%20(before%20and%20after%20you%20improve%20the%20speed)%20for%20each%20of%20the%203%20problematic%20queries.)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
## Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [x] The second query screenshot `SELECT * FROM visits where vet_id = 2;`  shows after improvements that the execution time is higher than before the improvements please work on that and remember to add  BEFORE on the first screenshot and AFTER on the second screenshot to make it easier to review them

### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Emmyn5600 — APPROVED** [review]
Hi Team

Good job👏🏼

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewers.

 #### Optional suggestions
 -  N/A.
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by OLIPLICHE** [comment]
Thank you

**Pull request merged**
